### PR TITLE
Let promise rejection propagate in handleSubmit

### LINKED ISSUE #2758: The `onSubmit` promise rejection is not propagated
### Current Behavior

When a promise is returned in the `onSubmit` function and this promise is rejected, the rejection is not propagated. It seems the promise rejection is caught in the `handleSubmit` implementation ([here](https://github.com/formium/formik/blob/6cef617b42d64abb56f29fbc92f3f13e82ca5bab/packages/formik/src/Formik.tsx#L844)) to just print a warning to the console.

This behavior prevent users from catching unhandled rejections of submitted forms in a general way, such as `window.addEventListener("unhandledrejection", ...)`. The only workaround would be to add a `.catch(..)` on the promise of every `onSubmit`, which will cause the code to be very repetitive and hard to maintain.

It is possible to propagate the rejection of the promise in the `handleSubmit` implementation without affecting anything else? If so, I'll be happy to open a PR with the change 🙂 

### Expected behavior

The rejection of a promise on the `onSubmit` function is propagated so it could be handled by a global handler such as `window.addEventListener("unhandledrejection", ...)`

### Reproducible example

https://codesandbox.io/s/formik-codesandbox-template-forked-63xtg?file=/index.js

### Suggested solution(s)

Remove the catch block in the [handleSubmit` implementation](https://github.com/formium/formik/blob/master/packages/formik/src/Formik.tsx#L844)

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.1.5
| React            | 16.13.1
| TypeScript       | 4.0.3
| Browser          | Google Chrome
| npm/Yarn         | Yarn 1.22.4
| Operating System | Windows 10 Pro

### PR DESCRIPTION
**Pull request by JoseLion**
Resolve #2758

### CODE REVIEW

**Comment by JoseLion** [comment]
@johnrom I have updated this branch. Can we reopen this PR? 🙂

**Comment by hixus** [comment]
Please open this mr. The catch blocks us to seeing submit errors in Sentry. Therefore we don't know if something failed in the case we forgot to add our own catch.

**Comment by johnrom** [comment]
I'm getting an error trying to reopen this because it seems there was a hit force-push done to the branch? I think it will have to be recreated.

**Comment by JoseLion** [comment]
🤔 it was probably when I rebased to update the branch. I'll take a look 🙂

**Comment by JoseLion** [comment]
@johnrom I opened a new PR for this fix (#3341). Please let me know if you need anything else from my side. I'll be happy to help 🙂

**Pull request closed without merging**
