### PR TITLE
fix[FastField]: initial values in case of radio and checkbox

### PR DESCRIPTION
**Pull request by maddhruv**
Resolves - https://github.com/formium/formik/issues/2297

As FastField doesn't set initial values when the input type is radio or checkbox

### CODE REVIEW

**Comment by jaredpalmer** [comment]
Can you add a changeset ?

**Comment by maddhruv** [comment]
@jaredpalmer added the changelog

**Review by jaredpalmer — APPROVED** [review]

**Comment by maddhruv** [comment]
@all-contributors please add maddhruv for bug code content doc example ideas projectManagement question review

**Comment by johnrom** [comment]
@maddhruv @jaredpalmer this changeset migrated FastField from using formik.handleChange to field.onChange which could technically be a breaking change. Just a note in case we see FastField issues pop up.

**Comment by jaredpalmer** [comment]
Oof you’re totally right. Shoot

**Comment by royhadad** [comment]
how can I get this fix in my own project? is there a specific version I need to install? currently using 2.2.4

**Pull request merged**
